import json
import oracledb
import os

# Lista para armazenar as propriedades
propriedades = []

# Função para adicionar uma propriedade rural
def adicionar_propriedade(nome, hectares_plantados, toneladas_colhidas, toneladas_perdidas):
    propriedade = {
        'nome': nome,
        'hectares_plantados': hectares_plantados,
        'toneladas_colhidas': toneladas_colhidas,
        'toneladas_perdidas': toneladas_perdidas,
        'percentual_perda': calcular_perda(toneladas_colhidas, toneladas_perdidas)
    }
    propriedades.append(propriedade)

# Função para calcular percentual de perda
def calcular_perda(colhidas, perdidas):
    if colhidas + perdidas == 0:
        return 0.0
    return round((perdidas / (colhidas + perdidas)) * 100, 2)

# Função para salvar os dados em um arquivo JSON
def salvar_json(caminho_arquivo):
    with open(caminho_arquivo, 'w', encoding='utf-8') as f:
        json.dump(propriedades, f, indent=4, ensure_ascii=False)

# Função para conectar e inserir no banco Oracle
def inserir_banco(usuario, senha, dsn):
    try:
        connection = oracledb.connect(user=usuario, password=senha, dsn=dsn)
        cursor = connection.cursor()
        
        cursor.execute('''
            BEGIN
                EXECUTE IMMEDIATE '
                CREATE TABLE propriedades (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                    nome VARCHAR2(100),
                    hectares_plantados NUMBER,
                    toneladas_colhidas NUMBER,
                    toneladas_perdidas NUMBER,
                    percentual_perda NUMBER,
                    PRIMARY KEY (id)
                )';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
        ''')
        connection.commit()

        for propriedade in propriedades:
            cursor.execute('''
                INSERT INTO propriedades (nome, hectares_plantados, toneladas_colhidas, toneladas_perdidas, percentual_perda)
                VALUES (:1, :2, :3, :4, :5)
            ''', (
                propriedade['nome'],
                propriedade['hectares_plantados'],
                propriedade['toneladas_colhidas'],
                propriedade['toneladas_perdidas'],
                propriedade['percentual_perda']
            ))
        connection.commit()
        print("Dados inseridos no banco com sucesso!")
    except Exception as e:
        print(f"Erro ao inserir no banco: {e}")

# Função principal para usar o sistema
def menu():
    while True:
        print("\nControle de Perdas na Colheita de Cana-de-Açúcar")
        print("1. Adicionar Propriedade")
        print("2. Salvar Dados em JSON")
        print("3. Enviar Dados para Banco Oracle")
        print("4. Listar Propriedades")
        print("5. Sair")
        escolha = input("Escolha uma opção: ")

        if escolha == '1':
            nome = input("Nome da Propriedade: ")
            try:
                hectares = float(input("Hectares Plantados: "))
                colhidas = float(input("Toneladas Colhidas: "))
                perdidas = float(input("Toneladas Perdidas: "))
                adicionar_propriedade(nome, hectares, colhidas, perdidas)
                print("✅ Propriedade adicionada!")
            except ValueError:
                print("❌ Erro: Digite valores numéricos válidos!")

        elif escolha == '2':
            salvar_json('propriedades.json')
            print("✅ Dados salvos em propriedades.json!")

        elif escolha == '3':
            usuario = os.getenv('ORACLE_USER')
            senha = os.getenv('ORACLE_PASSWORD')
            dsn = os.getenv('ORACLE_DSN')
            if usuario and senha and dsn:
                inserir_banco(usuario, senha, dsn)
            else:
                print("❌ Variáveis de ambiente para Oracle não configuradas.")

        elif escolha == '4':
            if propriedades:
                for prop in propriedades:
                    print(f"🏡 {prop['nome']} - Perda: {prop['percentual_perda']}%")
            else:
                print("⚠️ Nenhuma propriedade cadastrada.")

        elif escolha == '5':
            print("👋 Saindo...")
            break
        else:
            print("❌ Opção inválida!")

# Iniciar o menu
if __name__ == "__main__":
    menu()

