services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=123456
      - ORACLE_DATABASE=XE
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: controle-perdas
    depends_on:
      oracle-db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "controle_perdas.py"]
    stdin_open: true      # <--- ADICIONE ISSO
    tty: true             # <--- ADICIONE ISSO
    environment:
      - ORACLE_USER=system
      - ORACLE_PASSWORD=123456
      - ORACLE_DSN=oracle-db/XE

